export const synapseDataTeam = [
    {
        id: 1,
        name: "Maksim Shatokhin",
        email: "mshatokhin@sfedu.ru",
        age: 21,
        phone: "(988) 899 98 74",
        access: "admin",
    },
    {
        id: 2,
        name: "Ivan Ma",
        email: "haihanich@yandex.ru",
        age: 24,
        phone: "(999) 519 42 17",
        access: "manager",
    },
    {
        id: 3,
        name: "Ivan Lynegov",
        email: "1wdyz11@gmail.com",
        age: 21,
        phone: "(995) 667 84 37",
        access: "manager",
    },
    {   id: 4,
        name: "Julia ",
        email: "juliailysowa555@mail.ru",
        age: 21,
        phone: "(919) 325 79 83",
        access: "manager",
    },
    {   id: 5,
        name: "Artem",
        email: "mshatokhin@sfedu.ru",
        age: 21,
        phone: "(988) 899 98 74",
        access: "manager",
    },
]